/*
 * Responsive image build.
 *
 * Writes AVIF and WebP width variants next to every photograph in public/media,
 * then regenerates src/media-manifest.js with the widths that actually exist per
 * format, so srcset never points at a file that was never built.
 *
 *   node scripts/build-media.mjs          build what is missing
 *   node scripts/build-media.mjs --force  rebuild everything
 *
 * AVIF lands first in the <picture> because it is roughly a third smaller than
 * the same WebP; WebP catches the browsers that miss it, and the original
 * JPEG/PNG stays as the <img> src for anything older still.
 *
 * Needs ffmpeg and ffprobe on PATH. Brand marks are skipped: they are fixed
 * size and already small.
 */
import { execFile } from "node:child_process";
import { promisify } from "node:util";
import { readdir, writeFile } from "node:fs/promises";
import { existsSync } from "node:fs";
import path from "node:path";

const run = promisify(execFile);
const MEDIA = path.resolve("public/media");
const PUBLIC = path.resolve("public");
const WIDTHS = [480, 960, 1440];
const SKIP = /sunray-logo-/i;
const force = process.argv.includes("--force");

const FORMATS = [
  {
    name: "avif",
    args: (file, width, out) => [
      "-v", "error", "-y", "-i", file,
      "-vf", `scale=${width}:-2:flags=lanczos`,
      "-c:v", "libaom-av1", "-still-picture", "1",
      "-crf", "32", "-cpu-used", "6",
      "-pix_fmt", "yuv420p", out,
    ],
  },
  {
    name: "webp",
    args: (file, width, out) => [
      "-v", "error", "-y", "-i", file,
      "-vf", `scale=${width}:-2:flags=lanczos`,
      "-c:v", "libwebp", "-quality", "78", "-compression_level", "6",
      "-pix_fmt", "yuv420p", out,
    ],
  },
];

async function walk(dir) {
  const out = [];
  for (const entry of await readdir(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) out.push(...(await walk(full)));
    else if (/\.(jpe?g|png)$/i.test(entry.name) && !SKIP.test(entry.name)) out.push(full);
  }
  return out;
}

async function widthOf(file) {
  const { stdout } = await run("ffprobe", [
    "-v", "error", "-select_streams", "v:0",
    "-show_entries", "stream=width", "-of", "csv=p=0", file,
  ]);
  return Number.parseInt(stdout.trim(), 10);
}

const sources = await walk(MEDIA);
const manifest = {};
let built = 0;

for (const file of sources) {
  const srcWidth = await widthOf(file);
  const base = file.replace(/\.(jpe?g|png)$/i, "");
  const available = {};

  for (const format of FORMATS) {
    for (const width of WIDTHS) {
      if (width > srcWidth) continue;
      const out = `${base}-${width}.${format.name}`;

      if (force || !existsSync(out)) {
        await run("ffmpeg", format.args(file, width, out));
        built += 1;
      }
      (available[format.name] ??= []).push(width);
    }
  }

  if (Object.keys(available).length) {
    const url = `/${path.relative(PUBLIC, file).split(path.sep).join("/")}`;
    manifest[url] = available;
  }
}

const header = [
  "/*",
  " * Generated by scripts/build-media.mjs — do not edit by hand.",
  " *",
  " * Maps each source photograph to the widths that exist beside it per format,",
  " * so srcset never points at a variant that was never built (small sources are",
  " * not upscaled).",
  " */",
  "",
].join("\n");

await writeFile("src/media-manifest.js", `${header}export const mediaVariants = ${JSON.stringify(manifest, null, 2)};\n`);

console.log(`sources: ${sources.length}  variants written: ${built}  manifest entries: ${Object.keys(manifest).length}`);
